// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    FormFieldError: typeof import('./src/components/Form/FormFieldError.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarAdmin: typeof import('./src/components/Sidebar/SidebarAdmin.vue')['default']
    'SidebarAdmin copy': typeof import('./src/components/Sidebar/SidebarAdmin copy.vue')['default']
    SidebarItem: typeof import('./src/components/Sidebar/SidebarItem.vue')['default']
    SidebarProfile: typeof import('./src/components/Sidebar/SidebarProfile.vue')['default']
  }
}

export {}
